backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "home"
    label: "Home"
    folder: "src/pages/home"
    create: true
    fields:
      - label: "Template Key" 
        name: "templateKey" 
        widget: "hidden" 
        default: "home-page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Hero" 
        name: "hero"
        widget: "object"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Text"
            name: "text"
            widget: "text"
          - label: "Video"
            name: "video"
            widget: "file"
          - label: "Background"
            name: "background"
            widget: "image"
      - label: "Reviews"
        name: "reviews"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "User"
            name: "user"
            widget: "string"
          - label: "Rank"
            name: "rank"
            widget: "select"
            options: ["5", "4", "3", "2", "1"]
            default: 5
            require: true
          - label: "Text"
            name: "text"
            widget: "text"
      - label: "Products"
        name: "products"
        widget: "object"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Product List"
            name: "pruductList"
            widget: "list"
            fields:
              - label: "Icon"
                name: "icon"
                widget: "image"
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Actions"
                name: "actions"
                widget: "list"
              - label: "Price"
                name: "price"
                widget: "number"
                valueType: "int"
              - label: "Period"
                name: "period"
                widget: "select"
                options: ["hr", "day", "week", "month"]
              - label: "Taxes"
                name: "taxes"
                widget: "string"
              - label: "Fees"
                name: "fees"
                widget: "string"
      - label: "Icons" 
        name: "icons"
        widget: "object"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - label: "Icon"
                name: "icon"
                widget: "image"
      - label: "Call to action"
        name: "callToAction"
        widget: "object"
        required: false
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Text"
            name: "text"
            widget: "text"
      - label: "Features"
        name: "features"
        widget: "list"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Text"
            name: "text"
            widget: "text"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Video"
            name: "video"
            widget: "file"
          - label: "Align"
            name: "align"
            widget: "select"
            options: ["Right", "Left"]
      - label: "Contact Footer"
        name: "contactFooter"
        widget: "object"
        required: false
        fields: 
          - label: "Title 1"
            name: "title1"
            widget: "string"
          - label: "Contact Icons"
            name: "contactIcons"
            widget: "list"
            fields:
                - label: "Icon"
                  name: "icon"
                  widget: "image"
                - label: "URL"
                  name: "url"
                  widget: "string"
          - label: "Social Icons"
            name: "socialIcons"
            widget: "list"
            fields:
                - label: "Icon"
                  name: "icon"
                  widget: "image"
                - label: "URL"
                  name: "url"
                  widget: "string"
          - label: "Text"
            name: "text"
            widget: "string"
          - label: "Title 2"
            name: "title2"
      - label: "Footer"
        name: "Footer"
        widget: "object"
        fields:
          - label: "Text"
            name: "text"
            widget: "string"
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
          - label: "Copyright"
            name: "copyright"
            widget: "string"

  - name: "media"
    label: "Media"
    folder: "src/pages/media"
    fields:
      - label: "Template Key" 
        name: "templateKey" 
        widget: "hidden" 
        default: "media-page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Press Release"
        name: "pressrelease"
        widget: "list"
        fields:
          - label: "Item"
            name: "item"
            widget: "relation"
            collection: "pressrelease"
            searchFields: ["title", "subtitle"]
            displayFields: ["title"]
            valueField: "title"
      - label: "Media Coverage"
        name: "mediacoverage"
        widget: "list"
        fields:
          - label: "Item"
            name: "item"
            widget: "relation"
            collection: "mediacoverage" 
            searchFields: ["title", "excerpt"]
            displayFields: ["title"]
            valueField: "title"

  - name: "pressrelease"
    label: "Press Release"
    folder: "src/pages/pressrelease"
    create: true
    fields:
      - label: "Template Key" 
        name: "templateKey" 
        widget: "hidden" 
        default: "press-post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        widget: "text"
      - label: "Website"
        name: "website"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        format: "MMMM D, YYYY"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "mediacoverage"
    label: "Media Coverage"
    folder: "src/pages/mediacoverage"
    create: true
    fields:
      - label: "Template Key" 
        name: "templateKey" 
        widget: "hidden" 
        default: "media-post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
      - label: "Website"
        name: "website"
        widget: "string"
      - label: "URL"
        name: "url"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        format: "MMMM D, YYYY"
      - label: "Logo"
        name: "logo"
        widget: "image"